version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=your-secret-key-here
      - DATABASE_TYPE=sqlite
      - DATABASE_PATH=/app/data/bifrost.db
      - BIFROST_ADMIN_USERNAME=admin
      - BIFROST_ADMIN_EMAIL=admin@bifrost.local
      - BIFROST_ADMIN_PASSWORD=changeme
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped